# Nicolas Oyeleye, 19359231 - Operating Systems Project 2
# 2021-ca216-scheduling/

fcfs: schedule_fcfs.py driver.py schedule.txt
	python schedule_fcfs.py schedule.tct

sjf: schedule_sjf.py driver.py schedule.txt
	python schedule_sjf.py schedule.txt

rr: schedule_rr.py driver.py schedule.txt
	python schedule_rr.py schedule.txt

priority: schedule_sjf.py driver.py schedule.txt
	python schedule_priority.py schedule.txt
